- name: "gpt-4"
  provider: "openai"
  model_type: "chat"
  max_tokens: 4096
  temperature: 0.7
  cost_per_1k_tokens: 0.03
  description: "OpenAI GPT-4 model for general tasks"

- name: "gpt-3.5-turbo"
  provider: "openai"
  model_type: "chat"
  max_tokens: 4096
  temperature: 0.7
  cost_per_1k_tokens: 0.002
  description: "OpenAI GPT-3.5 Turbo for cost-effective tasks"

- name: "gpt-4o"
  provider: "openai"
  model_type: "chat"
  max_tokens: 128000
  temperature: 0.7
  cost_per_1k_tokens: 0.005
  description: "OpenAI GPT-4o for large context tasks"

- name: "claude-3-opus"
  provider: "anthropic"
  model_type: "chat"
  max_tokens: 200000
  temperature: 0.7
  cost_per_1k_tokens: 0.015
  description: "Anthropic Claude 3 Opus for complex reasoning"

- name: "claude-3-sonnet"
  provider: "anthropic"
  model_type: "chat"
  max_tokens: 200000
  temperature: 0.7
  cost_per_1k_tokens: 0.003
  description: "Anthropic Claude 3 Sonnet for balanced performance"

- name: "gemini-pro"
  provider: "google"
  model_type: "chat"
  max_tokens: 32768
  temperature: 0.7
  cost_per_1k_tokens: 0.0005
  description: "Google Gemini Pro for cost-effective tasks"

- name: "text-embedding-3-small"
  provider: "openai"
  model_type: "embedding"
  dimensions: 1536
  cost_per_1k_tokens: 0.00002
  description: "OpenAI text embedding model"

- name: "text-embedding-3-large"
  provider: "openai"
  model_type: "embedding"
  dimensions: 3072
  cost_per_1k_tokens: 0.00013
  description: "OpenAI large text embedding model"

- name: "glm-4.5"
  provider: "glm"
  model_type: "chat"
  max_tokens: 128000
  temperature: 0.7
  cost_per_1k_tokens: 0.003
  description: "GLM 4.5 for advanced reasoning and code generation" 