# Governance Policies for Sophie Reflex Orchestrator

# Human-in-the-Loop (HITL) Policies
hitl:
  enabled: true
  approval_threshold: 0.7  # Minimum trust score for auto-approval
  rejection_threshold: 0.4  # Maximum trust score for auto-rejection
  timeout_seconds: 300  # Time to wait for human intervention
  
  # Conditions requiring human review
  require_human_review:
    - trust_score < 0.6
    - confidence_score < 0.5
    - contains_sensitive_content: true
    - high_risk_task: true
    - iteration_count > 10
  
  # Auto-approval conditions
  auto_approve:
    - trust_score >= 0.8
    - confidence_score >= 0.7
    - iteration_count < 5
    - no_interventions: true

# Agent Lifecycle Policies
agent_lifecycle:
  # Pruning conditions
  prune_agents:
    - trust_score < 0.3
    - consecutive_failures > 3
    - performance_decline: 0.2
  
  # Forking conditions
  fork_agents:
    - trust_score > 0.8
    - high_performance: true
    - unique_solution: true
  
  # Mutation conditions
  mutate_agents:
    - trust_score < 0.6
    - stagnant_performance: true
    - diversity_needed: true

# Trust Management Policies
trust:
  initial_score: 0.5
  max_score: 1.0
  min_score: 0.0
  
  # Trust score adjustments
  adjustments:
    successful_execution: +0.1
    failed_execution: -0.2
    human_approval: +0.15
    human_rejection: -0.25
    high_quality_output: +0.05
    low_quality_output: -0.1
  
  # Trust decay
  decay:
    enabled: true
    rate: 0.01  # Per iteration
    max_decay: 0.3

# Resource Limits
resource_limits:
  max_concurrent_agents: 10
  max_memory_usage: "1GB"
  max_execution_time: 300  # seconds per agent
  max_total_iterations: 100
  
  # Rate limiting
  rate_limits:
    requests_per_minute: 60
    tokens_per_minute: 10000

# Security Policies
security:
  content_filtering:
    enabled: true
    block_categories:
      - "hate_speech"
      - "violence"
      - "adult_content"
      - "illegal_activities"
  
  data_privacy:
    encrypt_sensitive_data: true
    retention_days: 30
    anonymize_logs: true
  
  access_control:
    require_authentication: false  # For demo purposes
    audit_all_actions: true

# Performance Policies
performance:
  optimization_goals:
    - minimize_latency
    - maximize_quality
    - balance_diversity
  
  monitoring:
    track_metrics:
      - "trust_scores"
      - "execution_times"
      - "success_rates"
      - "human_interventions"
      - "resource_usage"
  
  alerts:
    low_trust_score: 0.3
    high_failure_rate: 0.5
    resource_exhaustion: 0.8