# Optimized System Configuration for Sophie Reflex Orchestrator (Modular Architecture)

# API Keys and Authentication
api_keys:
  openrouter: "" # Set your OpenRouter API key here

# Model Configuration
models:
  default: "openai" # Logical tag; routed via OpenRouter
  openai:
    model: "openai/gpt-4o"
    temperature: 0.7
    max_tokens: 2000
    timeout: 30
    max_retries: 3
  google:
    model: "google/gemini-pro"
    temperature: 0.7
    max_tokens: 2000
    timeout: 30
    max_retries: 3
  anthropic:
    model: "anthropic/claude-3.5-sonnet"
    temperature: 0.7
    max_tokens: 2000
    timeout: 30
    max_retries: 3

# Memory Backend Configuration
memory:
  backend: "chromadb" # Options: chromadb, sqlite-vss
  chromadb:
    host: "chromadb"
    port: 8000
    collection_name: "sophie_memory"
    embedding_model: "all-MiniLM-L6-v2"
    distance_metric: "cosine"
  sqlite-vss:
    db_path: "./memory/sophie_memory.db"
    dimension: 1536

# System Settings
system:
  max_agents: 10
  max_iterations: 100
  trust_threshold: 0.7
  hitl_enabled: true
  ui_port: 8001
  log_level: "INFO"
  debug_mode: false
  performance_mode: true

# HITL Configuration
hitl:
  enabled: true
  approval_threshold: 0.7
  timeout: 300
  auto_approve_threshold: 0.9

# GA Loop Configuration (Optimized for Modular Architecture)
genetic_algorithm:
  population_size: 5
  mutation_rate: 0.1
  crossover_rate: 0.3
  elite_count: 2
  max_generations: 50
  convergence_threshold: 0.95
  max_execution_time: 3600 # 1 hour
  parallel_execution: true
  batch_size: 10

# Component Configuration
components:
  agent_manager:
    max_concurrent_agents: 5
    timeout: 30
    retry_attempts: 3
  evaluation_engine:
    parallel_evaluation: true
    evaluation_timeout: 60
    min_evaluators: 1
  hitl_manager:
    enabled: true
    timeout: 300
    auto_approve_threshold: 0.9
  trust_manager:
    decay_rate: 0.1
    min_trust_score: 0.1
    max_trust_score: 1.0
  memory_manager:
    max_entries: 10000
    cleanup_interval: 3600
    compression_enabled: true
  population_manager:
    max_population_size: 20
    pruning_threshold: 0.3
    diversity_threshold: 0.7

# Performance and Caching
performance:
  cache_enabled: true
  cache_ttl: 3600
  max_memory_usage: "2GB"
  gc_threshold: 1000
  async_operations: true
  connection_pool_size: 10

# Monitoring and Observability
monitoring:
  enabled: true
  metrics_port: 9090
  health_check_interval: 30
  log_aggregation: true
  tracing_enabled: false
  jaeger_endpoint: "http://jaeger:14268"

# Security Settings
security:
  api_key_validation: true
  rate_limiting: true
  max_requests_per_minute: 100
  cors_enabled: true
  allowed_origins: ["*"]

# Database Configuration
database:
  type: "sqlite" # Options: sqlite, postgresql
  sqlite:
    path: "./memory/sophie.db"
    timeout: 30
  postgresql:
    host: "localhost"
    port: 5432
    database: "sophie"
    username: "sophie"
    password: ""

# Redis Configuration
redis:
  host: "redis"
  port: 6379
  db: 0
  password: ""
  max_connections: 10
  connection_timeout: 5

# Logging Configuration
logging:
  level: "INFO"
  format: "json"
  handlers:
    - console
    - file
  file:
    path: "./logs/sophie.log"
    max_size: "100MB"
    backup_count: 5
